/**
 * The follow-up note to a recruiter, composed so the wording is right every
 * time.
 *
 * No model writes any of it. The note is a fixed skeleton whose slots are
 * filled from facts the system has already verified and the person has
 * already approved: the posting's title and company as recorded, the two
 * requirements the scorer matched most strongly, two lines from THIS
 * application's tailored résumé (already grounded, already vetted for
 * recruiter-facing language) turned into the first person, and one proof
 * line with a number. What cannot be filled that way is left for the
 * person, marked, never improvised.
 *
 * Voice: plain, warm, short. Under 180 words. Never mentions salary, the
 * match score, attachments, or that a system was involved. Points back to
 * the application already in the recruiter's system.
 */
import { isRecruiterFacing } from "../render/languageQuality.ts";
import { AI_TERMS, STARTUP_TERMS } from "../render/tailoredDoc.ts";

export interface OutreachInput {
  company: string;
  title: string;
  /** ISO date the application was submitted, if it was. */
  appliedOn: string | null;
  recruiterName: string | null;
  /** The strongest matched requirements, best first (the ✓ lines on the job card). */
  requirements: string[];
  /** The tailored résumé's claim lines for this application. */
  resumeLines: string[];
  /** The posting's own words, for the AI / startup hook. */
  postingText: string;
  profile: { preferredName: string | null; firstName: string; lastName: string; phone: string | null; linkedin: string | null };
}

export interface OutreachDraft {
  subject: string;
  body: string;
  /** True when a slot could not be filled from approved material; the body says where. */
  needsYourWords: boolean;
  /** Anything the checks objected to. Empty means the note passed every rule. */
  problems: string[];
}

/** Lines that begin with what the person did can be said in the first person. */
const VERBS = /^(?:Built|Led|Managed|Taught|Designed|Executed|Produced|Assessed|Worked|Supervised|Translated|Created|Ran|Developed|Coordinated|Launched|Grew|Operated|Analy[sz]ed|Researched|Delivered|Owned|Drove|Implemented|Established|Maintained|Wrote|Planned|Oversaw|Directed|Organi[sz]ed|Trained|Mentored|Handled|Improved|Reduced|Increased|Negotiated|Prepared|Presented|Supported|Set up|Shipped)\b/;
export function firstPerson(line: string): string | null {
  const t = line.trim().replace(/\s+/g, " ");
  if (!VERBS.test(t)) return null;
  const sentence = t.charAt(0).toLowerCase() + t.slice(1);
  return `I ${sentence}${/[.!?]$/.test(sentence) ? "" : "."}`;
}

const tokens = (s: string) => new Set(s.toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter((w) => w.length >= 4));
const overlap = (a: Set<string>, b: Set<string>) => [...a].filter((w) => b.has(w)).length;
const HAS_NUMBER = /\d/;
const RENTPUP = /property-compliance|rentpup|rental-property/i;
const FORBIDDEN = /\b(?:salary|compensation|match score|my score|as an ai|an ai wrote|generated by|attached|attachment|resume attached)\b/i;

export function composeOutreach(i: OutreachInput): OutreachDraft {
  const problems: string[] = [];
  const name = `${i.profile.preferredName ?? i.profile.firstName} ${i.profile.lastName}`.trim();
  const ai = AI_TERMS.test(i.postingText);
  const startup = STARTUP_TERMS.test(i.postingText);
  const reqs = i.requirements.filter(Boolean).slice(0, 3);
  const reqTokens = tokens(reqs.join(" "));

  // Candidate lines: first-person-able, recruiter-facing, ranked by how
  // much they speak to the matched requirements; RentPup first when the
  // posting is about AI or startups, as on the résumé.
  const candidates = i.resumeLines
    .map((line) => ({ line, said: firstPerson(line) }))
    .filter((c): c is { line: string; said: string } => Boolean(c.said) && isRecruiterFacing(c.line))
    .map((c) => ({ ...c, score: overlap(tokens(c.line), reqTokens) * 3 + ((ai || startup) && RENTPUP.test(c.line) ? 4 : 0) + (HAS_NUMBER.test(c.line) ? 1 : 0) }))
    .sort((a, b) => b.score - a.score);
  const bridge = candidates.slice(0, 2);
  const proof = candidates.find((c) => HAS_NUMBER.test(c.line) && !bridge.includes(c)) ?? null;

  const when = i.appliedOn ? ` on ${new Date(i.appliedOn).toLocaleDateString("en-US", { month: "long", day: "numeric" })}` : "";
  const hook = ai ? "The AI focus of the role is what drew me to it."
    : startup ? "A team building at an early stage is where I do my best work."
    : reqs.length ? `The emphasis on ${reqs.slice(0, 2).join(" and ")} is close to the work I do best.`
    : "";

  let needsYourWords = false;
  const bridgeText = bridge.length ? bridge.map((c) => c.said).join(" ")
    : (needsYourWords = true, "[Two sentences in your words about why your background fits this role.]");
  const proofText = proof ? proof.said : "";

  const paragraphs = [
    `Hi ${i.recruiterName?.trim() || "there"},`,
    `I applied for the ${i.title} role at ${i.company}${when} and wanted to reach out directly.${hook ? ` ${hook}` : ""}`,
    bridgeText,
    proofText,
    "If it's useful, I'm glad to talk through any of this. Thanks for your time.",
    [name, [i.profile.phone, i.profile.linkedin].filter(Boolean).join(" · ")].filter(Boolean).join("\n"),
  ].filter((p) => p.trim().length > 0);
  const body = paragraphs.join("\n\n");
  const subject = `Application for ${i.title} at ${i.company} — ${name}`;

  // The rules, checked on the finished text.
  const words = body.split(/\s+/).filter(Boolean).length;
  if (words > 180) problems.push(`${words} words; the note must stay under 180`);
  if (!needsYourWords && /\[[^\]]+\]/.test(body)) problems.push("a placeholder was left in the text");
  if (FORBIDDEN.test(body)) problems.push("the note mentions something it must not (pay, score, attachments, or the system)");
  if (!i.company.trim() || !i.title.trim()) problems.push("the company or role name is missing");
  for (const c of bridge) if (!isRecruiterFacing(c.said)) problems.push(`not recruiter-facing: ${c.said.slice(0, 60)}`);
  return { subject, body, needsYourWords, problems };
}
