/**
 * Master resume composition.
 *
 * Two rules shape this file, and they are in tension with how a resume is
 * normally written:
 *
 *   1. Every line traces to a frozen profile row. The composer reframes
 *      stored evidence into resume voice; it never adds a fact, a number,
 *      a date, a scope or an adjective that the evidence does not carry.
 *   2. Nothing is generated by a model. A generator writes flattering
 *      prose by default, and the failure mode this project keeps hitting
 *      is a true-sounding sentence nobody can trace. Static composition
 *      makes every claim reviewable against its source.
 *
 * Where a metric exists, its approved_wording is used verbatim. That
 * wording was negotiated once and it does not get improved here.
 */
import type { NameParts } from "./names.ts";
import { isRecruiterFacing, assertRecruiterFacing } from "./languageQuality.ts";
import { projectClaims, mayBeReframed } from "./projectEvidence.ts";
import { consolidateEmployment, orderForRecruiter, orderForPresentation,
         type EmploymentPeriod, type EmploymentRelationship } from "./relationships.ts";

export const RESUME_COMPOSER_VERSION = 1;

export interface FrozenRow { source_table: string; row_id: string; row_data: any }

export interface ResumeLine {
  text: string;
  /** Row ids this line was reframed from. Empty is not allowed. */
  sources: string[];
}
export interface ResumeRole {
  employer: string; title: string; location: string | null;
  start: string; end: string | null; startPrecision: string; endPrecision: string;
  lines: ResumeLine[];
  /**
   * Every real period, when one entry presents several.
   *
   * Two stints at one employer read as two jobs, which is accurate about
   * the records and misleading about the person: a reader scanning the
   * page sees an employer twice and has to reconstruct that it is one
   * relationship interrupted. Presenting them under one heading fixes
   * that, but only honestly, and honestly means printing every range.
   *
   * So this is not a merged span. It is a list of the actual periods,
   * rendered in full, and the chronology guard admits the entry only
   * when each one matches a recorded position and none is left out. An
   * entry that showed "2019 to Present" over these two periods would
   * assert continuous employment and is still refused.
   */
  periods?: Array<{ start: string; end: string | null; startPrecision: string; endPrecision: string }>;
}
/**
 * A link on the resume, with its display text separate from where it goes.
 *
 * These are the same today. They will not be: the portfolio link is
 * going to read "tylerpleban.com" while pointing at a destination
 * specific to one application, so a visit can be attributed to the
 * application that produced the resume. Keeping text and href as one
 * string now would mean either an ugly URL on the page or a rewrite of
 * the renderer later.
 */
/**
 * A project on the resume: a stable identity line, and any number of
 * optional claims beneath it.
 *
 * The two are different kinds of thing. `line` says what the project is
 * and is always printed when the project is; `optional` says what it
 * does, and every one of those has to earn its space against this
 * particular posting exactly as an employment bullet does.
 */
export interface ResumeProject {
  name: string;
  /** An optional presentation title rendered directly under the name
   *  heading, the way an experience shows a role under its org line. */
  title?: string;
  line: ResumeLine;
  /** Candidate claims, before relevance selection has dropped any. */
  optional: ResumeLine[];
  /** Claims whose wording is fixed to the evidence, by row id. */
  fixedWording?: string[];
}

export interface ResumeLink {
  /** What a reader sees. Always the plain, professional form. */
  text: string;
  /** Where it actually goes. */
  href: string;
}

export interface ResumeDoc {
  name: string; email: string; phone: string | null; location: string;
  links: ResumeLink[];
  summary: ResumeLine;
  roles: ResumeRole[];
  education: Array<{ institution: string; credential: string; field: string | null }>;
  skillGroups: Array<{ label: string; skills: string[] }>;
  projects: ResumeProject[];
}

/** The professional form of a URL: no scheme, no trailing slash, no query. */
export function displayUrl(url: string): string {
  return url.replace(/^https?:\/\//i, "").replace(/^www\./i, "").replace(/\/+$/, "");
}

const MONTHS = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];

/**
 * A date at the precision the record actually holds.
 *
 * MONTH precision used to render as the bare year, which threw away a
 * fact the profile had confirmed. It matters here: the second Genius One
 * stint began in March 2024, and a reader given only "2024" beside a
 * Holley entry ending in 2024 cannot tell how long the interruption was.
 * YEAR precision still renders as the year alone, because that is all
 * those records establish.
 */
const YEAR = (d: string | null, precision: string) =>
  d === null ? "Present"
    : precision === "MONTH" ? `${MONTHS[Number(d.slice(5, 7)) - 1]} ${d.slice(0, 4)}`
      : d.slice(0, 4);

/**
 * Skills are grouped by what a reader is scanning for, not by the
 * profile's own level enum. Level decides inclusion, not placement:
 * EXPOSURE-level skills are left off entirely rather than listed beside
 * things he can actually do.
 */
const SKILL_GROUPS: Array<[string, string[]]> = [
  // WHAT THE GENERAL RESUME SHOWS, not everything that is verified.
  //
  // The profile stays broad on purpose: tailoring needs the full set,
  // and a skill absent from a job's requirements still matters when
  // that job asks. This list is the recruiter-facing selection, and it
  // is shorter than the profile deliberately.
  //
  // Two rules decided what stayed. Capabilities beat tool names, because
  // "Audience segmentation" says what he can do and "Omnisend" says what
  // he has opened; the tools that survive are the ones a reader screens
  // on. And the creative group is cut hardest, not because the work was
  // not real, but because a long list of Adobe applications pulls the
  // whole page toward video production and away from the marketing,
  // product and operations identity the entries actually prove.
  ["Marketing and ecommerce", [
    "Email marketing", "Marketing funnel design", "Audience segmentation",
    "Campaign execution", "Campaign measurement and attribution", "SEO", "Ecommerce",
    "Paid advertising", "Omnisend", "Google Analytics", "Shopify", "Website development", "Branding",
  ]],
  ["Product development", [
    "Product ideation", "Iterative product development", "Launching a new offering",
    "Requirements definition", "Functional prototyping", "Design for manufacturing",
    "Parametric CAD", "Onshape", "FDM 3D printing", "Conversion testing",
  ]],
  ["Operations and process", [
    "Project coordination", "Workflow design", "Workflow automation", "Process improvement",
    "Asana", "Cross-department collaboration", "Tool and service evaluation",
    "Solution development", "Client needs assessment", "Staff supervision",
    // Folded in rather than given their own heading. Excel and Sheets
    // are screened on for operations roles and stay; a separate "Office
    // and productivity tools" line spent a heading and its spacing to
    // say less than the line it now sits in.
    "Microsoft Excel", "Google Sheets", "Microsoft PowerPoint",
  ]],
  // Kept, and kept short. Real and differentiating capability, but not
  // the identity this resume argues for, so it gets one line rather than
  // fourteen entries of Adobe applications. Named individually because
  // the allowlist keeps only VERIFIED skill names, and "Adobe Creative
  // Suite" is not one of them: inventing a collective label to save a
  // line would put a skill on the page the profile does not contain.
  ["Creative production", [
    "Video production", "Video editing", "Motion graphics", "Graphic design", "Photography",
    "Adobe Premiere Pro", "Adobe After Effects", "Adobe Photoshop",
  ]],
  ["Technical", [
    "AI-assisted development", "Claude Code", "Supabase", "Vercel", "Stripe",
    "Subscription billing", "Third-party service integration",
  ]],
  // Four verified skills that could not reach a resume at all.
  //
  // SKILL_GROUPS is an allowlist: composeResume keeps only the verified
  // skills that appear in it, so a skill absent from every group is
  // invisible to employer-facing output however well established it is.
  // These four were added to the profile as VERIFIED after a screening
  // read pointed out their absence, and they stayed invisible because
  // nothing added them here.
  //
  // Listed individually and never collapsed. "Microsoft Office" and
  // "Google Workspace" are broader claims than the evidence supports:
  // the user confirmed four named tools, not two suites, and a suite
  // name would assert Access, Outlook, Apps Script and the rest along
  // with them. The heading is a category, not a claim.
  //
  // Relevance is already handled downstream and is not weakened here.
  // selectCapabilities scores every skill against the posting, drops
  // anything scoring zero, and prints a heading only when at least two
  // survive, so these appear when a job asks for them and are absent
  // otherwise. See scoreCapability in relevance.ts.
];

export function composeResume(rows: FrozenRow[], name: NameParts, displayName: string): ResumeDoc {
  const of = (t: string) => rows.filter((r) => r.source_table === t);
  const profileRow = of("profile")[0];
  if (!profileRow) throw new Error("version snapshot has no profile row");
  const profile = profileRow.row_data;

  const metrics = of("metrics");
  const metric = (label: string): FrozenRow => {
    const m = metrics.find((r) => r.row_data.label === label);
    if (!m) throw new Error(`approved metric not found: ${label}. The resume will not invent one.`);
    return m;
  };
  /** Uses an approved metric's wording verbatim, carrying its provenance. */
  const fromMetric = (label: string, lead = "", tail = ""): ResumeLine => {
    const m = metric(label);
    return { text: `${lead}${m.row_data.approved_wording}${tail}`, sources: [m.row_id] };
  };

  const emp = of("employment_records")
    .sort((a, b) => (b.row_data.start_month ?? "").localeCompare(a.row_data.start_month ?? ""));
  const roleRow = (employer: string, start: string) =>
    emp.find((r) => r.row_data.employer === employer && (r.row_data.start_month ?? "").startsWith(start))!;

  const g1now = roleRow("Genius One, Inc.", "2024");
  const g1old = roleRow("Genius One, Inc.", "2019");
  const apNow = roleRow("Anytime Picture LLC", "2024");
  const apOld = roleRow("Anytime Picture LLC", "2019");
  const holley = roleRow("Holley Performance", "2022");
  // The Asana automation statement, cited directly so the sentence
  // points at the row that contains it rather than at the employment
  // record, which does not mention Asana at all.
  const holleyAsana = of("evidence").find((e) =>
    String(e.row_data.summary ?? "").startsWith("Identified and implemented unused automation capability"));
  const lccc = roleRow("Lorain County Community College", "2016");

  const role = (r: FrozenRow, lines: ResumeLine[]): ResumeRole => ({
    employer: r.row_data.employer,
    title: r.row_data.display_title ?? r.row_data.actual_title,
    location: r.row_data.location ?? null,
    start: r.row_data.start_month, end: r.row_data.end_month,
    startPrecision: r.row_data.start_precision ?? "YEAR",
    endPrecision: r.row_data.end_precision ?? "YEAR",
    lines,
  });

  // The summary states span, breadth and the two things the evidence
  // actually supports at scale: taking loose objectives to implementation,
  // and working across marketing, product and operations. No adjectives
  // that the profile cannot back.
  // The closing clause used to read "in small teams where the same person
  // scopes the work and delivers it", stated across all four roles. Asked
  // directly who worked out what each piece of work required, Ty answered
  // that it varied: strongest at Genius One, where the owner gave an
  // objective and he determined the approach; more limited at Anytime
  // Picture and the college, where the project or the responsibility was
  // already set and he decided how to accomplish it; and not
  // representative of Holley, where he worked within established projects
  // and priorities. So the blanket version is gone, and what remains is
  // the part that holds everywhere: he takes loosely defined objectives
  // through to implementation, which the Genius One record states in
  // those words.
  // The project row is cited by the summary, so it is looked up here
  // rather than only where the projects section is built below.
  const rentpupProject = of("projects").find((p) => p.row_data.name === "RentPup");
  // Cited by the summary's traction clause, so its words rest on the
  // rows that establish them rather than on the project description.
  // The row that establishes the end of the product lifecycle. The
  // employment records describe designing and prototyping; "repeated
  // production and commercial sale" is this evidence and the bullet has
  // to cite it, not merely be true alongside it.
  const g1Product = of("evidence").find((e) =>
    String(e.row_data.summary ?? "").startsWith("Designed and developed physical products for Genius One"));
  const rentpupUsers = of("metrics").find((m) => m.row_data.label === "RentPup current users");
  const rentpupRevenue = of("metrics").find((m) => m.row_data.label === "RentPup current monthly revenue");
  // The previous version opened "Experience since 2016 spanning
  // ecommerce and email marketing, physical product development..." and
  // was assembled entirely from true parts: 2016 is in the college
  // record and every domain appears across the cited rows. It still
  // asserted something the evidence does not support, because a reader
  // takes "since 2016" to govern the list and ecommerce, email marketing
  // and physical product development all begin at Genius One in 2019.
  // The temporal-scope gate now refuses it; see lib/render/temporalScope.ts.
  //
  // What replaces it carries no date at all. The through-line is the
  // thing that actually holds across five entries in four occupations:
  // a stated need is taken to a working solution, and the objectives are
  // loosely defined at the start. Each predicate rests on a cited row --
  // business needs and practical solutions on Anytime Picture, loosely
  // defined objectives on the earlier Genius One stint, troubleshooting
  // on both, and the independent product on the RentPup project row.
  //
  // The opener names an identity, and it is taken from the record rather
  // than invented: "Digital Marketing, Product & Operations Specialist"
  // is the VERIFIED title at Genius One across both stints, so
  // "marketing, product, and operations" is his own job title read back.
  //
  // It deliberately does not say "generalist". That word is a scoring
  // concept, useful internally for candidacy, and as recruiter-facing
  // copy it labels breadth instead of showing it, which reads as a
  // hedge about depth. The breadth is demonstrated by the span in the
  // second sentence and by the entries below, each carrying its own
  // cited evidence.
  // Written last, against what the entries below actually prove.
  //
  // The previous version described a way of working and then listed the
  // domains it happened in. Both sentences were true and neither said
  // what came of it. The entries now carry three finished things: a
  // product line that reached production and sale, an offering built to
  // its revenue peak, and an independent product in use and earning. So
  // the summary names the pattern once and points at outcomes, and the
  // entries prove it.
  //
  // Every word is checked against what the record supports. "Takes
  // loosely defined objectives through to implementation" is the Genius
  // One record's own wording. "Builds and operates" is what RentPup
  // establishes and nothing more: not founded, not scaled, not a
  // business. There is no year count, no seniority claim, no ownership
  // of strategy, and no adjective the profile cannot back. It does not
  // say generalist, which labels breadth instead of showing it.
  const summary: ResumeLine = {
    // Every content word here is carried by a row this sentence cites.
    //
    // The previous wording ("builds the solution rather than handing off
    // the requirements ... now in use") read well and was refused by the
    // provenance gate on tailoring: "rather", "off" and "now" appear in
    // the profile but not in any row the summary cited, and the gate
    // will not let a sentence rest on rows that do not contain its
    // words. The master generator does not run that gate, so it passed
    // there and failed on every application, which is the more important
    // of the two.
    //
    // The traction clause cites the two RentPup metrics directly, so "in
    // use" and "generating revenue" rest on the rows that establish
    // them. The numbers stay in the RentPup entry rather than being
    // restated here.
    text: "Marketing, product, and operations specialist who takes loosely defined business objectives through to "
        + "implementation, across ecommerce and email marketing, physical products taken from concept through "
        + "production, and internal processes. Work includes an independent property-compliance product built "
        + "outside of full-time work, in use and generating revenue.",
    sources: [g1old.row_id, g1now.row_id, holley.row_id, lccc.row_id, apOld.row_id,
      ...(rentpupProject ? [rentpupProject.row_id] : []),
      ...(rentpupUsers ? [rentpupUsers.row_id] : []),
      ...(rentpupRevenue ? [rentpupRevenue.row_id] : [])],
  };

  // Bullets are written against the PERIOD they came from, and stay
  // attached to it. Consolidation below decides which entry a period is
  // printed under; it never changes which evidence a sentence cites.
  const byPeriod = new Map<string, ResumeLine[]>();
  const linesOf = (r: FrozenRow, lines: ResumeLine[]) => { byPeriod.set(r.row_id, lines); return role(r, lines); };

  const periodEntries: ResumeRole[] = [
    // The current stint carries no bullets of its own. Everything Genius
    // One supports is printed once, under the consolidated entry built
    // below, because splitting it across two headings made the reader
    // reassemble one body of work from two halves.
    // The current Genius One period: the AI contact-analysis system, in
    // Ty's own words (2026-09-07), recorded on the employment record as
    // accomplishments. The contact figure is the approved audience
    // metric, cited so its scope guard travels with it.
    linesOf(g1now, [
      { text: "Built an AI system that analyzes how approximately 180,000 contacts behave and what they buy, identifying who is about to buy, who is slipping away, who is price-shopping, and who is worth holding onto.",
        sources: [g1now.row_id, metric("Email audience size worked with at Genius One").row_id] },
      { text: "Use the same behavioral and purchase signals to forecast product demand, since current campaign activity indicates what will be needed on hand later, and to decide which marketing tests are worth running before running them.",
        sources: [g1now.row_id] },
    ]),
    // The current Anytime Picture period contributes no bullets, on
    // purpose.
    //
    // It used to carry "Deliver video production and client solutions
    // work on a part-time contract basis", every substantive word of
    // which is already printed directly above it: the entry is titled
    // "Video Production & Client Solutions Specialist (Part-Time
    // Contract)". Stripped of its own title, employer and location
    // words, the sentence had nothing left, and it was the only bullet
    // in the profile of which that was true -- the next-thinnest still
    // had eleven words of its own. It reached the page on 1,113 of
    // 4,658 postings and told a reader nothing on any of them.
    //
    // Nothing replaces it. The title, the dates and the employment
    // relationship already state what this period was, and no evidence
    // for the period supports a further claim. A period with nothing to
    // add contributes nothing, which the composition has always
    // allowed; writing a sentence to fill the space would be the
    // padding this project exists to avoid.
    linesOf(apNow, []),
    linesOf(holley, [
      { text: "Produced creative work across multiple brands, internal teams, and concurrent projects with shifting priorities and deadlines.", sources: [holley.row_id] },
      { text: "Collaborated cross-functionally with marketing and other teams to set creative approaches and run projects from planning through delivery.", sources: [holley.row_id] },
      // Replaces a list of the content types produced, which named
      // formats rather than saying anything a reader could act on.
      //
      // Every clause is bounded by the evidence's own scope guard: Asana
      // was already in use, he did not introduce or select it, and what
      // he contributed was recognizing and configuring automation the
      // team had not used. "Configured" and "already in use" are both
      // load-bearing words here.
      // The evidence's own vocabulary, deliberately.
      //
      // A first wording said "defined conditions" and "bringing in the
      // right people as work progressed", which reads better and rests
      // on words the cited rows do not contain: the gate found "bring"
      // nowhere in the profile at all. The record says conditions he set
      // and people automatically involved, so that is what this says.
      // "Already used" keeps the scope guard visible: he did not
      // introduce or select Asana.
      { text: "Configured automated workflows in Asana, which the team already used, moving projects between teams on conditions and automatically involving the right people.", sources: [holleyAsana!.row_id, holley.row_id] },
      { text: "Supported broader marketing initiatives through creative production, scripts, content publishing, and SEO-oriented metadata.", sources: [holley.row_id] },
    ]),
    linesOf(g1old, [
      // PHYSICAL PRODUCT, first, because it is the strongest and least
      // replaceable thing here.
      //
      // The earlier pair of bullets said "contributed to product
      // ideation" and then "designed, prototyped, tested and refined",
      // which read as someone assisting with ideas and separately doing
      // some prototyping. Both rows actually describe one lifecycle, and
      // the corrected evidence adds the end of it: these products reached
      // repeated production and commercial sale. Said once, in order,
      // it is the same evidence and a truer picture.
      {
        text: "Design and develop physical products using FDM 3D printing, taking original concepts through parametric CAD in Onshape, "
            + "prototyping, material selection, tolerance testing, and iterative functional testing into repeated production and commercial sale.",
        sources: [g1old.row_id, g1now.row_id, ...(g1Product ? [g1Product.row_id] : [])],
      },
      // The commercial result, kept as its own sentence. The metric's
      // wording is used verbatim so its scope guard travels with it: the
      // figure is product SALES, never revenue he generated, and never
      // stated alongside the Genius Academy figure.
      fromMetric("Sales of 3D-printed products designed at Genius One", "", "."),
      fromMetric("Email audience size worked with at Genius One", "", "."),
      fromMetric("Genius Academy annual recurring revenue", "", "."),
      // "Takes loosely defined objectives through to implementation" now
      // opens the summary, so the bullet that said it again is gone: the
      // page should not spend three lines making one point twice.
      // The stakeholder-coordination line went with it. It was true and
      // it asked a reader to be impressed by having colleagues.
      { text: "Executed digital marketing and ecommerce work across websites, SEO, email, analytics, content, creative production, and online storefronts, and researched emerging products and technologies at industry trade shows.", sources: [g1old.row_id] },
    ]),
    linesOf(apOld, [
      { text: "Translated client goals into practical production solutions within budget, timeline, creative, and technical constraints.", sources: [apOld.row_id] },
      { text: "Worked directly with clients to understand business needs, develop solutions, troubleshoot challenges, and deliver finished projects.", sources: [apOld.row_id] },
      { text: "Worked personally on client projects for Cleveland Clinic and Amazon showcasing a new laboratory and a newly opened warehouse, covering planning, filming, editing, motion graphics, and graphic design.", sources: [apOld.row_id] },
      { text: "Supported client acquisition and sales by speaking with prospects, assessing needs, recommending solutions, and closing projects by phone.", sources: [apOld.row_id] },
    ]),
    linesOf(lccc, [
      // The metric carries the count; the employment record carries the
      // technical concepts and professional workflows. The metric alone
      // says only that he taught 250+ students.
      (() => {
        const m = metric("Students taught and mentored");
        return {
          text: `${m.row_data.approved_wording}, translating technical concepts and professional workflows into hands-on instruction.`,
          sources: [m.row_id, lccc.row_id],
        };
      })(),
      // Two halves, two sources. The metric covers the supervision; the
      // employment record covers the lab operations. Citing only the
      // metric left the second half unprovenanced, which the grounding
      // checks caught in Stage 2 validation: a sentence can be entirely
      // true and still be unsupported by what it points at.
      (() => {
        const m = metric("Student employees supervised");
        return {
          text: `${m.row_data.approved_wording}, and managed day-to-day lab operations.`,
          sources: [m.row_id, lccc.row_id],
        };
      })(),
      // Same correction as the supervision line: the metric covers the
      // deliverable count, the employment record covers the show and the
      // editing work. Citing only the metric left most of the sentence
      // unprovenanced.
      (() => {
        const m = metric("Video deliverables in the national television collaboration");
        return {
          text: `${m.row_data.approved_wording} with the production company behind a nationally broadcast show that aired three seasons on the Sportsman Network, and personally edited portions of the show and created motion graphics for it.`,
          sources: [m.row_id, lccc.row_id],
        };
      })(),
      { text: "Maintained and troubleshot professional production technology, and researched and evaluated emerging technology as part of a major equipment modernization initiative.", sources: [lccc.row_id] },
    ]),
  ];

  // Where a person has confirmed that separate periods were one
  // continuous relationship, the resume says so once. Genius One
  // appearing as 2019-2022 and again as 2024-present is accurate about
  // the records and wrong about the relationship: it reads as a break
  // that did not happen. Without a confirmed relationship record the
  // periods stay exactly as they are.
  const relationshipRows = of("employment_relationships");
  const relationships: EmploymentRelationship[] = relationshipRows.map((r) => ({
    id: r.row_id,
    employer: r.row_data.employer,
    displayTitle: r.row_data.display_title,
    location: r.row_data.location ?? null,
    qualifier: r.row_data.employer_facing_qualifier ?? null,
    start: r.row_data.relationship_start,
    end: r.row_data.relationship_end ?? null,
    startPrecision: r.row_data.start_precision ?? "YEAR",
    endPrecision: r.row_data.end_precision ?? "YEAR",
    employmentType: r.row_data.employment_type,
    workload: r.row_data.workload ?? "UNKNOWN",
    coveredRecordIds: r.row_data.covered_record_ids ?? [],
    continuityBasis: r.row_data.continuity_basis ?? "",
    confirmedBy: r.row_data.confirmed_by ?? "",
  }));

  const periods: EmploymentPeriod[] = emp.map((r) => ({
    id: r.row_id,
    employer: r.row_data.employer,
    title: r.row_data.display_title ?? r.row_data.actual_title,
    location: r.row_data.location ?? null,
    start: r.row_data.start_month,
    end: r.row_data.end_month ?? null,
    startPrecision: r.row_data.start_precision ?? "YEAR",
    endPrecision: r.row_data.end_precision ?? "YEAR",
    isCurrent: Boolean(r.row_data.is_current),
    employmentType: r.row_data.employment_type ?? null,
  }));

  // Chronology decides the order; one explicit presentation rule then
  // moves the lead employer to the front. See orderForPresentation.
  /**
   * One entry per employer where the same job was held more than once.
   *
   * Presentation only, and it asserts nothing the records do not hold:
   * every real period is printed beside the heading, so the interruption
   * is visible rather than papered over. The bullets are the union of
   * what each period contributed, in the order they were written.
   *
   * This is not the continuous-relationship path below it. That one
   * needs someone to state the relationship never stopped, and prints a
   * single merged span. Genius One had a genuine interruption during
   * Holley, so no such record exists and none should.
   */
  const consolidateRepeatedEmployer = (entries: ResumeRole[]): ResumeRole[] => {
    const out: ResumeRole[] = [];
    const handled = new Set<string>();
    for (const e of entries) {
      if (handled.has(e.employer)) continue;
      const sameEmployer = entries.filter((x) => x.employer === e.employer);
      // Only where the title is the same job. Different titles at one
      // employer are a progression a reader should see.
      const sameTitle = sameEmployer.every((x) => x.title === e.title);
      if (sameEmployer.length < 2 || !sameTitle) { out.push(e); continue; }

      handled.add(e.employer);
      const byStart = [...sameEmployer].sort((a, b) => b.start.localeCompare(a.start));
      const newest = byStart[0]!;
      out.push({
        ...newest,
        periods: byStart.map((x) => ({
          start: x.start, end: x.end,
          startPrecision: x.startPrecision, endPrecision: x.endPrecision,
        })),
        // Oldest first, because the story reads forward and the earliest
        // stint is where most of the evidence sits.
        lines: [...byStart].reverse().flatMap((x) => x.lines),
      });
    }
    return out;
  };

  // Applied to whichever path produced the entries. Anytime Picture has
  // a confirmed continuous relationship and Genius One does not, so both
  // mechanisms are live at once and repeated-employer consolidation has
  // to run over the result of either.
  const roles: ResumeRole[] = orderForPresentation(consolidateRepeatedEmployer(
    relationships.length
      ? consolidateEmployment(periods, relationships, (id) => byPeriod.get(id) ?? [])
      : orderForRecruiter(periodEntries)));

  const skillNames = new Set(of("skills")
    .filter((r) => r.row_data.level !== "EXPOSURE")
    .map((r) => r.row_data.name as string));
  const skillGroups = SKILL_GROUPS
    .map(([label, names]) => ({ label, skills: names.filter((n) => skillNames.has(n)) }))
    .filter((g) => g.skills.length > 0);

  // Genius Academy is a verified project, but it belongs inside the
  // Genius One role where its approved ARR wording already sits. Listing
  // it separately would read as a second venture.
  // The project row describes what RentPup is for. What it does with
  // outside data is a separate confirmed statement, and the sentence
  // rests on both, so it cites both.
  const rentpupBehaviour = of("evidence")
    .find((e) => String(e.row_data.summary ?? e.row_data.statement ?? "").startsWith("RentPup automatically checks"));
  // "AI-assisted development" is a verified skill, and the sentence says
  // it was built that way. The skill row is where that word lives.
  const aiAssisted = of("skills").find((k) => k.row_data.name === "AI-assisted development");
  const projects: ResumeProject[] = of("projects")
    .filter((p) => p.row_data.name === "RentPup")
    .map((p) => {
      // What the project DOES comes from its linked evidence, not from
      // here. Adding a verified statement to the profile and linking it
      // is enough to put it in front of relevance selection; no edit to
      // this file is required, and none should be.
      const claims = projectClaims(p.row_id, rows);

      /**
       * What the general resume shows, out of everything RentPup can say.
       *
       * The project has seventeen confirmed claims and they are all true.
       * Printed together they read as product documentation: subsystem
       * inventories, notification spools, experiment infrastructure. A
       * recruiter is not evaluating the architecture, and the page it
       * cost was coming out of the rest of a career.
       *
       * The rest stay in the evidence system, where job-specific
       * tailoring can reach them. Nothing is deleted; this is selection.
       *
       * Chosen for what each one demonstrates rather than what it
       * describes: recurring monitoring of outside data, judgement about
       * what the data does not establish, an end-to-end workflow, and
       * scheduled automation that produces an outcome.
       */
      // Prefer verified claims that read as capability/outcome AND pass the
      // recruiter-facing language guard. The old fixed list hard-required an
      // evidence claim whose TEXT is engineering documentation ("a scheduled
      // job recomputes obligation statuses ... undelivered alerts spooled ...
      // reported to the operator"); it rendered verbatim into a submitted
      // PDF. Selection now skips any claim the guard flags, so internal-
      // documentation evidence can never become a bullet, and takes the most
      // recruiter-facing verified claims first.
      const PREFERRED = [
        // Ty's own wording (2026-09-07): what he built and how, then what it does.
        /from concept through launch/i,
        /monitor public records and regulatory changes/i,
        /points outreach toward the right prospects/i,
        /automatically checks .*data sources on a recurring/i,   // recurring public-record monitoring, no owner action
        /recognizes deadlines, identifies changes/i,             // deadlines + change detection + activity against the property
        /direct-mail measurement and attribution system/i,       // a built system, product/business framing
        /generates individuali[sz]ed direct-mail pieces/i,       // (guard drops it if the text carries "queue")
        /runs largely automatically/i,                           // outcome: little ongoing work to operate
      ];
      // Concise AND recruiter-facing: a résumé bullet is a clause, not a
      // paragraph, so a claim far longer than a normal bullet is skipped even
      // when it carries no implementation vocabulary.
      // 220, not 170: Ty's own first-person line for RentPup runs to two
      // rendered lines and is a single clause; it was being skipped for
      // length while implementation prose half its size got through.
      const CONCISE = 220;
      const recruiterClaims = claims.filter((c) =>
        isRecruiterFacing(c.line.text) && c.line.text.replace(/\s+/g, " ").trim().length <= CONCISE);
      const showcase: typeof claims = [];
      // Three, not two: the tailored path selects from this pool per posting,
      // and a business-development posting wants the prospecting line while
      // an operations posting wants the monitoring one.
      const SHOWCASE = 3;
      for (const rx of PREFERRED) {
        if (showcase.length >= SHOWCASE) break;
        const found = recruiterClaims.find((c) => rx.test(c.line.text) && !showcase.includes(c));
        if (found) showcase.push(found);
      }
      // Fill to at most two, from any remaining concise recruiter-facing
      // claim; never an implementation-prose or paragraph-length one. The
      // traction line leads, so the section is never empty even if none match.
      for (const c of recruiterClaims) { if (showcase.length >= SHOWCASE) break; if (!showcase.includes(c)) showcase.push(c); }

      // The traction facts lead, because they are what changed: this is
      // no longer only something he built, it is something in use.
      // Stated exactly as confirmed. Not customers, not subscribers, not
      // MRR, and never annualized.
      const users = metrics.find((m) => m.row_data.label === "RentPup current users");
      const revenue = metrics.find((m) => m.row_data.label === "RentPup current monthly revenue");
      const traction: ResumeLine[] = users && revenue
        ? [{
            text: `In use by ${users.row_data.numeric_value} users and generating approximately `
                + `$${Number(revenue.row_data.numeric_value).toLocaleString("en-US")} in monthly revenue.`,
            sources: [users.row_id, revenue.row_id],
          }]
        : [];

      return {
        // Employer-facing presentation, approved as an intentional title
        // change: RentPup shown as an independent product-building
        // experience, explicitly not employment. Hyphens, never em dashes.
        name: "RENTPUP - rentpup.com - Independent Product",
        title: "Founder / Product Builder",
        line: {
          // The verified project-row description, which is written
          // recruiter-facing ("A property-compliance monitoring product
          // helping Cleveland rental-property owners identify regulatory
          // issues and upcoming compliance risks"). Every word rests on the
          // project row; the fixed fallback keeps it grounded if the row has
          // no description. NOT an implementation summary from evidence.
          text: (typeof p.row_data.description === "string" && p.row_data.description.trim())
            ? String(p.row_data.description).trim()
            : "Property-compliance monitoring system built independently outside of full-time employment.",
          sources: [p.row_id],
        },
        optional: [...traction, ...showcase.map((c) => c.line)],
        fixedWording: claims.filter((c) => !c.reframable).flatMap((c) => c.line.sources),
      };
    });

  // General gate: no résumé line may read as engineering documentation.
  // The RentPup showcase already selects only recruiter-facing claims; this
  // catches any FUTURE source (any role or project) that would regress into
  // internals, before it can reach a submitted PDF.
  assertRecruiterFacing([
    ...roles.flatMap((r) => r.lines.map((l) => ({ text: l.text, where: r.title }))),
    ...projects.flatMap((p) => [{ text: p.line.text, where: p.name },
      ...p.optional.map((l) => ({ text: l.text, where: p.name }))]),
  ]);

  return {
    name: displayName,
    email: profile.email_job_search,
    phone: profile.phone ?? null,
    location: `${profile.city}, ${profile.state}`,
    links: [profile.linkedin_url, profile.portfolio_url, ...(profile.website_urls ?? [])]
      .filter(Boolean)
      .map((url: string) => ({ text: displayUrl(url), href: url })),
    summary, roles,
    education: of("education").map((e) => ({
      institution: e.row_data.institution, credential: e.row_data.credential, field: e.row_data.field_of_study ?? null,
    })).sort((a, b) => (b.credential ?? "").localeCompare(a.credential ?? "")),
    skillGroups, projects,
  };
}

/**
 * RentPup is the one entry where the flattering version is a lie: it is
 * pre-revenue with no verified customer traction, and it is built in his
 * own time rather than for an employer. The wording states what was
 * built and stops there.
 */
function projectLine(name: string, _description: string): string {
  if (name !== "RentPup") throw new Error(`no approved project wording for ${name}`);
  // The earlier wording said the system "ingests county and municipal
  // records, matches them to properties, and surfaces" issues. Ty
  // confirmed the behaviour and refused the machinery: checking is
  // automatic and recurring, and findings are associated with particular
  // properties, but nothing establishes that every source is downloaded
  // into a database, nor how often, nor how many there are. "Ingests"
  // claims an implementation; "checks" and "associates" claim what he
  // actually confirmed.
  return "Independent product, built outside of full-time work. A property-compliance monitoring system for Cleveland rental-property "
       + "owners that automatically checks city and county data sources on a recurring basis, associates what it finds with specific "
       + "properties, and identifies regulatory issues and upcoming compliance requirements. Built with AI-assisted development on "
       + "Supabase, Vercel, and Stripe.";
}

export function renderMarkdown(d: ResumeDoc): string {
  const dates = (r: ResumeRole) =>
    (r.periods?.length ? [...r.periods] : [r])
      .sort((a, b) => a.start.localeCompare(b.start))
      .map((p) => `${YEAR(p.start, p.startPrecision)} to ${p.end ? YEAR(p.end, p.endPrecision) : "Present"}`)
      .join(", ");
  const out: string[] = [];
  out.push(`# ${d.name}`);
  // A link whose destination differs from its text is written as a
  // markdown link, so the visible text stays clean and the destination
  // survives into whatever renders the PDF.
  const link = (l: ResumeLink) => (l.text === l.href ? l.text : `[${l.text}](${l.href})`);
  out.push([d.location, d.email, d.phone, ...d.links.map(link)].filter(Boolean).join(" | "));
  out.push("", "## Summary", "", d.summary.text);
  out.push("", "## Experience");
  for (const r of d.roles) {
    out.push("", `### ${r.title}`, `${r.employer}${r.location ? `, ${r.location}` : ""} | ${dates(r)}`, "");
    for (const l of r.lines) out.push(`- ${l.text}`);
  }
  if (d.projects.length) {
    out.push("", "## Projects");
    for (const p of d.projects) {
      out.push("", `### ${p.name}`);
      if (p.title) out.push(p.title);
      out.push("", p.line.text);
      if (p.optional.length) { out.push(""); for (const l of p.optional) out.push(`- ${l.text}`); }
    }
  }
  out.push("", "## Skills", "");
  for (const g of d.skillGroups) out.push(`**${g.label}:** ${g.skills.join(", ")}`, "");
  out.push("## Education", "");
  for (const e of d.education) out.push(`- ${e.credential}${e.field ? `, ${e.field}` : ""}, ${e.institution}`);
  return out.join("\n") + "\n";
}

/** Every line of employer-facing text, for validation. */
export function allLines(d: ResumeDoc): ResumeLine[] {
  return [d.summary, ...d.roles.flatMap((r) => r.lines),
    ...d.projects.flatMap((p) => [p.line, ...p.optional])];
}
