-- Two small changes: one removal, one accommodation.

-- ============================================================
-- 1. A numeric confidence has no business on an application answer
-- ============================================================
--
-- application_answers.confidence has sat unused since 0004. It is a
-- probability between 0 and 1, and the rule for this phase is that no
-- score, ratio, similarity or model confidence may ever justify
-- asserting an application fact. confidence_state is the only thing that
-- decides, and it is categorical on purpose.
--
-- A dormant numeric column is an invitation to reach for it later, which
-- is exactly the failure the rule exists to prevent.

alter table application_answers drop column if exists confidence;

-- ============================================================
-- 2. Application-specific portfolio attribution: the column only
-- ============================================================
--
-- Every tailored resume will eventually carry a portfolio link unique to
-- its application, so a visit can be attributed to the application that
-- produced it. None of that is built here: no endpoint, no analytics, no
-- redirect, no public route.
--
-- The column is added now because adding it later means migrating a
-- table that by then holds real applications, and because the resume
-- renderer's link model has to allow a per-application destination from
-- the start or it hard-codes a literal URL that is painful to undo.
--
-- What the token must be, and why:
--
--   OPAQUE. Cryptographically random, generated by the worker. It
--   encodes nothing: not the employer, the company, the job, the
--   application, the recruiter, the candidate, and no sequence number.
--   Two tokens side by side reveal no relationship, and neither can be
--   used to guess a third.
--
--   NULLABLE. No application has one until the portfolio exists. A
--   column that is required before its feature is built forces fake
--   values, and a fake opaque token is worse than none.
--
--   UNIQUE WHEN PRESENT. A token identifies exactly one application, or
--   it identifies nothing. The partial index enforces that without
--   making a table of nulls collide.
--
-- Attribution is at the level of an APPLICATION, never a person. The
-- defensible claim this supports is "someone used the link associated
-- with this application", not "a named recruiter opened it". A resume
-- gets forwarded, scanned by security tooling, parsed by an ATS and
-- opened by several people, and the design has to preserve that
-- uncertainty rather than resolve it.

alter table applications add column if not exists attribution_token text;

comment on column applications.attribution_token is
  'Opaque per-application portfolio attribution token. Cryptographically random, generated worker-side, encoding nothing about the employer, job, application, recruiter or candidate. Null until portfolio tracking is built. Attribution is application-level, never individual-level.';

-- Unique only among rows that have one.
create unique index if not exists applications_attribution_token_unique
  on applications (attribution_token) where attribution_token is not null;

-- Structural floor, so a short or non-random value cannot be stored by
-- mistake. This checks shape, not randomness; randomness is the
-- generator's job and is asserted in its tests.
alter table applications drop constraint if exists attribution_token_is_opaque;
alter table applications add constraint attribution_token_is_opaque
  check (attribution_token is null
         or (length(attribution_token) between 16 and 64
             and attribution_token ~ '^[A-Za-z0-9_-]+$'));

-- The token is a secret in the sense that guessing one reaches a real
-- application's link. It is never selected by the portal's read paths
-- for any purpose other than building the resume, and the public
-- portfolio does not exist yet. RLS already restricts every row of this
-- table to the owner, so no additional policy is needed today; when the
-- public resolver is built it will be a separate, narrowly scoped
-- function rather than a widened table grant.
